var pincodeSet = [
                  
                	  {
                	    "pincode":"400001",
                	    "FIELD2":"Fort",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400002",
                	    "FIELD2":"Kalbadevi",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400003",
                	    "FIELD2":"Mandvi",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400004",
                	    "FIELD2":"Girgaon",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400005",
                	    "FIELD2":"Colaba",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400006",
                	    "FIELD2":"Malabar Hill",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400007",
                	    "FIELD2":"Grant Road",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400008",
                	    "FIELD2":"Mumbai Central",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400009",
                	    "FIELD2":"Chinch B'der",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400010",
                	    "FIELD2":"Mazgaon",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400011",
                	    "FIELD2":"Jacob Circle",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400012",
                	    "FIELD2":"Parel",
                	    "set":"DR"
                	  },
                	  {
                	    "pincode":"400013",
                	    "FIELD2":"Delisle Road",
                	    "set":"DR"
                	  },
                	  {
                	    "pincode":"400014",
                	    "FIELD2":"Dadar (C. R.)",
                	    "set":"DR"
                	  },
                	  {
                	    "pincode":"400015",
                	    "FIELD2":"Sewree",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400016",
                	    "FIELD2":"Mahim",
                	    "set":"DR"
                	  },
                	  {
                	    "pincode":"400017",
                	    "FIELD2":"Dharavi",
                	    "set":"DR"
                	  },
                	  {
                	    "pincode":"400018",
                	    "FIELD2":"Worli",
                	    "set":"DR"
                	  },
                	  {
                	    "pincode":"400019",
                	    "FIELD2":"Matunga",
                	    "set":"DR"
                	  },
                	  {
                	    "pincode":"400020",
                	    "FIELD2":"Marine Lines",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400021",
                	    "FIELD2":"Nariman Point",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400022",
                	    "FIELD2":"Sion",
                	    "set":"DR"
                	  },
                	  {
                	    "pincode":"400023",
                	    "FIELD2":"Fort",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400024",
                	    "FIELD2":"Nehru Nagar",
                	    "set":"C"
                	  },
                	  {
                	    "pincode":"400025",
                	    "FIELD2":"Prabhadevi",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400026",
                	    "FIELD2":"Cumbala Hill",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400027",
                	    "FIELD2":"Jijamata Udyan",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400028",
                	    "FIELD2":"BS. Rd. Dadar",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400029",
                	    "FIELD2":"Airport",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400031",
                	    "FIELD2":"Wadala",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400032",
                	    "FIELD2":"Mantralaya",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400033",
                	    "FIELD2":"Tank Road",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400034",
                	    "FIELD2":"Tulsiwadi",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400035",
                	    "FIELD2":"Rajbhavan",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400036",
                	    "FIELD2":"A. K. Marg",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400037",
                	    "FIELD2":"Antop Hill",
                	    "set":"CH"
                	  },
                	  {
                	    "pincode":"400038",
                	    "FIELD2":"Ballard Pier",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400039",
                	    "FIELD2":"Council Hall",
                	    "set":"SB"
                	  },
                	  {
                	    "pincode":"400042",
                	    "FIELD2":"Bhandup (E)",
                	    "set":"C"
                	  },
                	  {
                	    "pincode":"400043",
                	    "FIELD2":"Shivaji Nagar",
                	    "set":"CH"
                	  },
                	  {
                	    "pincode":"400046",
                	    "FIELD2":"Govandi",
                	    "set":"CH"
                	  },
                	  {
                	    "pincode":"400049",
                	    "FIELD2":"Juhu",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400050",
                	    "FIELD2":"Bandra (W)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400051",
                	    "FIELD2":"Bandra (E)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400052",
                	    "FIELD2":"Khar",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400053",
                	    "FIELD2":"Azad Nagar",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400054",
                	    "FIELD2":"Santacruz (W)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400055",
                	    "FIELD2":"Santacruz (E)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400056",
                	    "FIELD2":"Ville Parle (W)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400057",
                	    "FIELD2":"Ville Parle (E)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400058",
                	    "FIELD2":"Andheri (W)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400059",
                	    "FIELD2":"J. B. Nagar",
                	    "set":"AG"
                	  },
                	  {
                	    "pincode":"400060",
                	    "FIELD2":"Jogeshwari",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400061",
                	    "FIELD2":"Versova",
                	    "set":"AG"
                	  },
                	  {
                	    "pincode":"400062",
                	    "FIELD2":"Goregaon (W)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400063",
                	    "FIELD2":"Goregaon (E)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400064",
                	    "FIELD2":"Malad (W)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400065",
                	    "FIELD2":"Aarey Colony",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400066",
                	    "FIELD2":"Borivali (E)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400067",
                	    "FIELD2":"Kandivili (W)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400068",
                	    "FIELD2":"Dahisar",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400069",
                	    "FIELD2":"Andheri (E)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400070",
                	    "FIELD2":"Kurla",
                	    "set":"C"
                	  },
                	  {
                	    "pincode":"400071",
                	    "FIELD2":"Chembur",
                	    "set":"CH"
                	  },
                	  {
                	    "pincode":"400072",
                	    "FIELD2":"Saki Naka",
                	    "set":"AG"
                	  },
                	  {
                	    "pincode":"400074",
                	    "FIELD2":"R. C. F. Chembur",
                	    "set":"CH"
                	  },
                	  {
                	    "pincode":"400075",
                	    "FIELD2":"Pant Nagar",
                	    "set":"CH"
                	  },
                	  {
                	    "pincode":"400076",
                	    "FIELD2":"I. I. T. Powai",
                	    "set":"AG"
                	  },
                	  {
                	    "pincode":"400077",
                	    "FIELD2":"Ghatkopar (E)",
                	    "set":"C"
                	  },
                	  {
                	    "pincode":"400078",
                	    "FIELD2":"Bhandup (W)",
                	    "set":"C"
                	  },
                	  {
                	    "pincode":"400079",
                	    "FIELD2":"Vikhroli",
                	    "set":"C"
                	  },
                	  {
                	    "pincode":"400080",
                	    "FIELD2":"Mulund (W)",
                	    "set":"C"
                	  },
                	  {
                	    "pincode":"400081",
                	    "FIELD2":"Mulund (E)",
                	    "set":"C"
                	  },
                	  {
                	    "pincode":"400082",
                	    "FIELD2":"Mulund Col.",
                	    "set":"C"
                	  },
                	  {
                	    "pincode":"400083",
                	    "FIELD2":"Tagore Nagar",
                	    "set":"C"
                	  },
                	  {
                	    "pincode":"400084",
                	    "FIELD2":"Barve Nagar",
                	    "set":"C"
                	  },
                	  {
                	    "pincode":"400085",
                	    "FIELD2":"B. A. R. C",
                	    "set":"CH"
                	  },
                	  {
                	    "pincode":"400086",
                	    "FIELD2":"Ghatkopar (W)",
                	    "set":"C"
                	  },
                	  {
                	    "pincode":"400087",
                	    "FIELD2":"N. I. T. I. E",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400088",
                	    "FIELD2":"Deonar",
                	    "set":"CH"
                	  },
                	  {
                	    "pincode":"400089",
                	    "FIELD2":"Tilak Nagar",
                	    "set":"CH"
                	  },
                	  {
                	    "pincode":"400090",
                	    "FIELD2":"Bangur Nagar",
                	    "set":"C"
                	  },
                	  {
                	    "pincode":"400092",
                	    "FIELD2":"Borivli (W)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400093",
                	    "FIELD2":"Chakala",
                	    "set":"AG"
                	  },
                	  {
                	    "pincode":"400094",
                	    "FIELD2":"Anushakti Nagar",
                	    "set":"CH"
                	  },
                	  {
                	    "pincode":"400095",
                	    "FIELD2":"Khardi",
                	    "set":"AG"
                	  },
                	  {
                	    "pincode":"400096",
                	    "FIELD2":"SEEPZ",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400097",
                	    "FIELD2":"Malad (E)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400098",
                	    "FIELD2":"Vidyanagari",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400099",
                	    "FIELD2":"Sahar",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400101",
                	    "FIELD2":"Kandivli",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400102",
                	    "FIELD2":"Jogeshwari (W)",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400103",
                	    "FIELD2":"M'peshwar",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"400104",
                	    "FIELD2":"Motilal Nagar",
                	    "set":"W"
                	  },
                	  {
                	    "pincode":"421506",
                	    "FIELD2":"AMBERNATH",
                	    "set":"CF"
                	  },
                	  {
                	    "pincode":"401301",
                	    "FIELD2":"Agashi",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421301",
                	    "FIELD2":"Aghai",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400708",
                	    "FIELD2":"Airoli",
                	    "set":"TH"
                	  },
                	  {
                	    "pincode":"421601",
                	    "FIELD2":"Alyani",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421301",
                	    "FIELD2":"Amane",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421501",
                	    "FIELD2":"Ambernath South",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400610",
                	    "FIELD2":"Apna Bazar",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401302",
                	    "FIELD2":"Arnala",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421301",
                	    "FIELD2":"Asangaon",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421102",
                	    "FIELD2":"Atali",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421301",
                	    "FIELD2":"Atgaon",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421504",
                	    "FIELD2":"Badlapur",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400608",
                	    "FIELD2":"Balkum",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401201",
                	    "FIELD2":"Bassein",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"401202",
                	    "FIELD2":"Bassein Road",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"400614",
                	    "FIELD2":"Belapur Node- v",
                	    "set":"NM"
                	  },
                	  {
                	    "pincode":"421002",
                	    "FIELD2":"Bhaji Market",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421603",
                	    "FIELD2":"Bhatsanagar",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401105",
                	    "FIELD2":"Bhayander East",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"401101",
                	    "FIELD2":"Bhayander West",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421308",
                	    "FIELD2":"Bhiwandi",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401501",
                	    "FIELD2":"Boisar",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"401701",
                	    "FIELD2":"Bordi",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421001",
                	    "FIELD2":"Bus Terminus",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421312",
                	    "FIELD2":"Chamble",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401503",
                	    "FIELD2":"Chinchani",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"400607",
                	    "FIELD2":"Chitalsar Manpada",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421601",
                	    "FIELD2":"Chondhe Colony",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401601",
                	    "FIELD2":"Dahanu",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"401602",
                	    "FIELD2":"Dahanu Road",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"401608",
                	    "FIELD2":"Dahanu Tps",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"400612",
                	    "FIELD2":"Dahisar",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421302",
                	    "FIELD2":"Dandekarwadi",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401610",
                	    "FIELD2":"Dapchari",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"400706",
                	    "FIELD2":"Darave",
                	    "set":"NM"
                	  },
                	  {
                	    "pincode":"400612",
                	    "FIELD2":"Dawle",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421402",
                	    "FIELD2":"Dhasai",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421201",
                	    "FIELD2":"Dombivali",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421203",
                	    "FIELD2":"Dombivali I.a.",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401206",
                	    "FIELD2":"Ganeshpuri",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421306",
                	    "FIELD2":"Ganeshwadi",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421403",
                	    "FIELD2":"Gegaon",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400701",
                	    "FIELD2":"Ghansoli",
                	    "set":"TH"
                	  },
                	  {
                	    "pincode":"401702",
                	    "FIELD2":"Gholvad",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"400602",
                	    "FIELD2":"Gokhale Road",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401603",
                	    "FIELD2":"Jawhar",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"400606",
                	    "FIELD2":"Jekegram",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400703",
                	    "FIELD2":"K.U.bazar",
                	    "set":"NM"
                	  },
                	  {
                	    "pincode":"421301",
                	    "FIELD2":"Kalher",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400605",
                	    "FIELD2":"Kalwa",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421301",
                	    "FIELD2":"Kalyan City",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421501",
                	    "FIELD2":"Kansai",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401607",
                	    "FIELD2":"Kasa",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421602",
                	    "FIELD2":"Kasara",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400601",
                	    "FIELD2":"Kasarvadavali",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421401",
                	    "FIELD2":"Kasegaon",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421306",
                	    "FIELD2":"Katemanivali",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400612",
                	    "FIELD2":"Kausa",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401401",
                	    "FIELD2":"Kelwa",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421301",
                	    "FIELD2":"Khadvali",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421601",
                	    "FIELD2":"Kharade",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421403",
                	    "FIELD2":"Kharid",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421312",
                	    "FIELD2":"Khupri",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421601",
                	    "FIELD2":"Khutghar",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421311",
                	    "FIELD2":"Kon",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421312",
                	    "FIELD2":"Kondhale",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400614",
                	    "FIELD2":"Konkan Bhavan",
                	    "set":"NM"
                	  },
                	  {
                	    "pincode":"400709",
                	    "FIELD2":"Kopar Khairne",
                	    "set":"TH"
                	  },
                	  {
                	    "pincode":"400603",
                	    "FIELD2":"Kopri Colony",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401703",
                	    "FIELD2":"Kosbad-hill",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421503",
                	    "FIELD2":"Kulgaon",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421401",
                	    "FIELD2":"Majgaon",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421605",
                	    "FIELD2":"Manda",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421102",
                	    "FIELD2":"Manivail",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401403",
                	    "FIELD2":"Manor",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421204",
                	    "FIELD2":"Manpada",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421312",
                	    "FIELD2":"Met",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"400710",
                	    "FIELD2":"Milleniu,m Business park",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401104",
                	    "FIELD2":"Mira",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"401107",
                	    "FIELD2":"Mira Road",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421102",
                	    "FIELD2":"Mohone",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"401604",
                	    "FIELD2":"Mokhada",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400612",
                	    "FIELD2":"Mumbra",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401209",
                	    "FIELD2":"Nallosapare E",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421601",
                	    "FIELD2":"Nandgaon",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"400602",
                	    "FIELD2":"Naupada",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421312",
                	    "FIELD2":"Nehroli",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"400706",
                	    "FIELD2":"Nerul Node-ii",
                	    "set":"NM"
                	  },
                	  {
                	    "pincode":"400706",
                	    "FIELD2":"Nerul Sec-48",
                	    "set":"NM"
                	  },
                	  {
                	    "pincode":"421505",
                	    "FIELD2":"Netaji Bazar",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421204",
                	    "FIELD2":"Nilje",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401304",
                	    "FIELD2":"Nirmal",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421502",
                	    "FIELD2":"O.E.ambernath",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421101",
                	    "FIELD2":"Padgha",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401404",
                	    "FIELD2":"Palghar",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"401207",
                	    "FIELD2":"Papdi",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421401",
                	    "FIELD2":"Patgaon",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421311",
                	    "FIELD2":"Pimplas",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421201",
                	    "FIELD2":"Ramnagar",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400607",
                	    "FIELD2":"Sandozbaugh",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400705",
                	    "FIELD2":"Sanpada",
                	    "set":"NM"
                	  },
                	  {
                	    "pincode":"421311",
                	    "FIELD2":"Saravali",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401405",
                	    "FIELD2":"Satpati",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421103",
                	    "FIELD2":"Shahad",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421601",
                	    "FIELD2":"Shahapur",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400601",
                	    "FIELD2":"Thane",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400601",
                	    "FIELD2":"Thane Bazar",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400603",
                	    "FIELD2":"Thane East",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400601",
                	    "FIELD2":"Thane R.s.",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421605",
                	    "FIELD2":"Titwala",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421401",
                	    "FIELD2":"Tulai",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400703",
                	    "FIELD2":"Turbhe",
                	    "set":"TH"
                	  },
                	  {
                	    "pincode":"421312",
                	    "FIELD2":"Uchat",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421001",
                	    "FIELD2":"Ulhasnagar-1",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421002",
                	    "FIELD2":"Ulhasnagar-2",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421004",
                	    "FIELD2":"Ulhasnagar-4",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421005",
                	    "FIELD2":"Ulhasnagar-5",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401102",
                	    "FIELD2":"Umbarpada",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"401106",
                	    "FIELD2":"Uttan",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421301",
                	    "FIELD2":"Vaitarna",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401204",
                	    "FIELD2":"Vajreshwari",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"401103",
                	    "FIELD2":"Vangaon",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421301",
                	    "FIELD2":"Varap",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401208",
                	    "FIELD2":"Vasai East ie",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"401202",
                	    "FIELD2":"Vasai Road e",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"400703",
                	    "FIELD2":"Vashi",
                	    "set":"NM"
                	  },
                	  {
                	    "pincode":"400703",
                	    "FIELD2":"Vashi Sec-26",
                	    "set":"NM"
                	  },
                	  {
                	    "pincode":"400703",
                	    "FIELD2":"Vashi-vii",
                	    "set":"NM"
                	  },
                	  {
                	    "pincode":"421604",
                	    "FIELD2":"Vashind",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"421305",
                	    "FIELD2":"Vidyashram",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"401605",
                	    "FIELD2":"Vikramgad",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"401303",
                	    "FIELD2":"Virar",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"401305",
                	    "FIELD2":"Virar East",
                	    "set":"WF"
                	  },
                	  {
                	    "pincode":"421202",
                	    "FIELD2":"Vishnunagar",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400604",
                	    "FIELD2":"Wagle I.e.",
                	    "set":"T"
                	  },
                	  {
                	    "pincode":"400706",
                	    "FIELD2":"jui nagar",
                	    "set":"NM"
                	  }
                	];

function getPincodeSetData(){
	return pincodeSet; 
}